# -*- coding: utf-8 -*-
"""CodeAlpha_Hangman_Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pZMOEiQCgDkzLEzSBhh0Dd6pluI-er_
"""

# CodeAlpha Internship
# Task 1: Hangman Game
# Developed by: Javeria Naseer

import random

# List of predefined words
words = ["apple", "mango", "python", "flower", "school"]

# Randomly choose a word
word = random.choice(words)

guessed_letters = []
wrong_guesses = 0
max_wrong = 6

print("🎮 Welcome to Hangman Game!")
print("Guess the word one letter at a time.")

while wrong_guesses < max_wrong:

    # Display guessed letters
    display = ""
    for letter in word:
        if letter in guessed_letters:
            display += letter + " "
        else:
            display += "_ "

    print("\nWord:", display)

    # Check if player has guessed the word
    if "_" not in display:
        print("\n🎉 Congratulations! You guessed the word:", word)
        break

    # Take user input
    guess = input("Enter a letter: ").lower().strip()

    # Validate input
    if len(guess) != 1 or not guess.isalpha():
        print("❌ Please enter only one alphabet letter.")
        continue

    # Check if already guessed
    if guess in guessed_letters:
        print("⚠️ You already guessed that letter.")
        continue

    guessed_letters.append(guess)

    # Check correct or wrong guess
    if guess not in word:
        wrong_guesses += 1
        print("❌ Wrong Guess!")
        print("Remaining Chances:", max_wrong - wrong_guesses)

# If all chances are used
if wrong_guesses == max_wrong:
    print("\n💀 Game Over!")
    print("The correct word was:", word)